Add homepage
alphayowakarindi/Hello-Microverse pull request #1
Opened 2022-05-24 22:17 UTC by alphayowakarindi

2022-05-24 22:33 UTC, tufoinnkuo10 requested changes
Hi @alphayowakarindi  

There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight
✅ You used the correct Github flow
✅ Documented your work professionally
✅ Good commit messages
✅ Used correct README template
✅ Added gitignore file

**Required Changes** ♻️
Check the comments under the review
- [x] please ensure that your linters are correctly set up and passing. you can check how to do that [here](https://github.com/microverseinc/linters-config/tree/master/html-css).
- [x] Ensure that your Pull Request has a descriptive title telling you what changes are inside.

- [ ] please Add a description summary to your pull request. you can do that by clicking the 3dots and choosing edit. 👇🏾 ;


![Screenshot (35)_LI](https://user-images.githubusercontent.com/65298048/170142311-b4348482-f92a-4ba2-acda-877b586c78e5.jpg)

Optional suggestions

- [optional] please your Branch should have a name of a feature or action (e.g. 'created_sidebar' or 'added_comments_section').
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-05-24 22:33 UTC, tufoinnkuo10 commented on .gitignore
> +test.md/
- [ ] please make sure your `test.md` file is actually being ignored. that is to say, it should not exist in your remote repository.

2022-05-25 01:08 UTC, alphayowakarindi commented on .gitignore
> +test.md/
@tufoinnkuo10 Thank you very much for the feedback. It's much appreciated. I've worked on each of the recommendations you recommended. I'd just like to add that the Linters/Webhint test fails wasn't due to the wrong setup but due to line breaks in my HTML document. After removing the line breaks all the tests passed.

2022-05-25 04:22 UTC, alphayowakarindi commented on .gitignore
> +test.md/
@tufoinnkuo10 My linter set up got a lot of mixups. I've redone it on my local machine and everything is working perfectly as expected. Should I delete this branch and make another pull request? Kindly advice?

2022-05-25 05:08 UTC, tufoinnkuo10 commented on .gitignore
> +test.md/
- Thank you for implementing the changes. you are not supposed to create a new branch or pull a request before submitting again. please fix it and resubmit under this same pull request. 😄

2022-05-25 06:49 UTC, alphayowakarindi commented on .gitignore
> +test.md/
By that you mean I push the working code on the same branch from my local repository. Right?

2022-05-25 08:09 UTC, Sahar-AbdelSamad approved these changes
## STATUS APPROVED 🎉 🎉

Hi @alphayowakarindi 👋 👋 , 

Great work implementing the changes requested by the previous reviewer 👏
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

✔️  All linters passed 💯
✔️ Correct use of Github flow 💯

## Optional suggestions

- [x] [OPTIONAL] great job using microverse's README template and customizing it to your project 👏 👏 However you still have to customize your contact information 😃 kindly update it. This way when a recruiter likes your work he can contact you 😃 👍 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-25 08:09 UTC, Sahar-AbdelSamad commented on index.html
>      <link rel="stylesheet" href="style.css">
- [ ] [OPTIONAL] As you can see in this line, you are referencing a CSS file with the name `style.css`, but your CSS file has the name 'styles.css' with `s`
This is not allowing the styling to be implemented. Kindly fix it so we can see the page with the yellow color 😄 as in the CSS file

2022-05-25 08:09 UTC, Sahar-AbdelSamad commented on .hintrc
> +>>>>>>> e118b06dfa104b0353219bb5aaf641a85818eec2
- [ ] [OPTIONAL] I believe you forgot those lines. Please remove then 😃

2022-05-26 14:31 UTC, alphayowakarindi commented on index.html
>      <link rel="stylesheet" href="style.css">
Hi @Sahar-AbdelSamad, thanks for the feedback. The yellow color should be visible now :smiley:

2022-05-26 14:35 UTC, alphayowakarindi commented on .hintrc
> +>>>>>>> e118b06dfa104b0353219bb5aaf641a85818eec2
@Sahar-AbdelSamad You are right. Fixed, thank you!

2022-05-26 14:54 UTC, merged